apply plugin: 'com.android.library'
apply from: '../build.dependencies.gradle'

android {
    namespace = 'com.qualcomm.ftcrobotcontroller'
    compileSdk 34

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 28

        buildConfigField "String", "APP_BUILD_TIME", "\"" + new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSSZ").format(new java.util.Date()) + "\""
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
